### ISSUE TITLE
samples/jobs.py fails with zoautil_py.exceptions.JobSubmitException?

### ISSUE THREAD

**Issue by samilaine** [IBM/zoau#69]
Taking the `samples/jobs.py` as it is and running it in the [IBM Z Explore](https://www.ibm.com/z/resources/zxplore) USS produces

````
/z/zXXXXX/py > python3 zoautil-examples-jobs.py 
Traceback (most recent call last):
  File "/z/zXXXXX/py/zoautil-examples-jobs.py", line 67, in <module>
    run_sample()
  File "/z/zXXXXX/py/zoautil-examples-jobs.py", line 36, in run_sample
    job_sample = jobs.submit(dsn_with_mem_sample_jcl)
  File "/usr/lpp/IBM/zoautil/lib/zoautil_py/jobs.py", line 55, in submit
    raise ZOAUException(response.stderr_response)
zoautil_py.exceptions.ZOAUException
````

This might be a quirk of the IBM Z Xplore system setup, which is, obviously, out of my reach, but in any case I think it might be a good idea to wrap the call to `jobs.submit()` within a `try...except` block and print out what exactly went wrong.

**Comment by AnthonyGiorgio** [comment]
I'm not using the IBM Z Xplore system at the moment, so could you provide the version ZOAU version that you're using there?

**Comment by AnthonyGiorgio** [comment]
We've made significant improvements to ZOAU in the v1.2 release stream.  I don't know what kind of authority you're given on this system, but perhaps [you could try installing](https://www.ibm.com/docs/en/zoau/1.2.0?topic=installing-configuring-zoa-utilities) a [newer ZOAU version](https://public.dhe.ibm.com/ibmdl/export/pub/software/htp/zos/tools/zoau/?C=M;O=D)?
